baseURL = "https://www.jamesgibbins.com/"
languageCode = "en-gb"
theme = "hugo-theme-nix"
pluralizelisttitles = false
title = "james"
# publishDir = "docs" # for github
enableRobotsTXT = true
# summaryLength = 100

[params]
  Name = "James"
  Author = "James"
  HeaderUsername = ""
  HeaderHostname = "james"
  About = ""
  ProfilePicture = "/img/hshysrot.gif" # /hugo/img for github
  Favicon = "favicon.ico" # /hugo/img for github

  Email = 'james@gibbins.me'
  GithubID = 'jamesdeluk'
  LinkedInID = 'jamgib'
  RedditID = 'jamesdeluk'
  StackOverflowID = '8680753/jamesdeluk'
  TwitterID = 'jamesdeluk'
  # Medium = 'jamesdeluk'

  googleAnalytics = "G-4T1FV3DWGP"

[menu]
  [[menu.header]]
    name = "about"
    url = "/about"
  [[menu.header]]
    identifier = "projects"
    name = "projects"
    url = "/projects"
  [[menu.header]]
    parent = "projects"
    name = "python"
    url = "/projects/python"
  [[menu.header]]
    parent = "projects"
    name = "bash"
    url = "/projects/bash"
  [[menu.header]]
    identifier = "articles"
    name = "articles"
    url = "/articles"
  [[menu.header]]
    parent = "articles"
    name = "reviews"
    url = "/articles/reviews"
  [[menu.header]]
    parent = "articles"
    name = "offensive-security"
    url = "/articles/offensive-security"
  [[menu.header]]
    parent = "articles"
    name = "digital-forensics"
    url = "/articles/digital-forensics"
  [[menu.header]]
    name = "notes"
    url = "/notes"
  [[menu.header]]
    name = "achievements"
    url = "/achievements"
  [[menu.header]]
    name = "search"
    url = "/search"

[outputFormats.SearchIndex]
baseName = "search"
mediaType = "application/json"

[outputs]
home = [ "HTML", "RSS", "SearchIndex" ]