baseURL = "jamesdeluk.github.io/hugo"
languageCode = "en-gb"
theme = "hugo-theme-nix"
pluralizelisttitles = false
title = "james"
publishDir = "docs"

[params]
  Name = "James"
  HeaderUsername = "user"
  HeaderHostname = "james"
  About = ""
  ProfilePicture = "/img/hshysrot.gif"
  Favicon = "/favicon.ico"

  # BitbucketID = "your_bitbucket_id"
  # CodepenID = "your_codepen"
  # CvURL = "your_cv_url"
  Email = 'jgibbins92@gmail.com'
  # FacebookID = "your_facebook"
  GithubID = 'jamesdeluk'
  # GitlabId = "your_gitlab"
  # GnuPGFingerprint = "your_gpg_fingerprint"
  # GoogleAnalytics = "your_google_analytics_id"
  # GoogleplusID = "your_googleplus"
  # InstagramID = "your_instagram"
  LinkedInID = 'jamgib'
  # MastodonURL = "your_mastodon_profile"
  # Mobile = "+1-201-555-0123"
  # PayPalMeID = "https://www.paypal.me/..."
  # Phone = "+1-201-555-0123"
  RedditID = 'jamesdeluk'
  # SlackURL = "https://join.slack.com/..."
  # StackExchangeID = "your_stackexchange_id"
  StackOverflowID = '8680753/jamesdeluk'
  # TelegramID = "your_telegram"
  TwitterID = 'jamesdeluk'
  # XingURL = "https://www.xing.com/profile/..."

[menu]
  [[menu.header]]
    name = "about"
    url = "/about"
  [[menu.header]]
    name = "posts"
    url = "/posts"
  [[menu.header]]
    identifier = "projects"
    name = "projects"
  [[menu.header]]
    parent = "projects"
    name = "python"
    url = "/python"
  [[menu.header]]
    parent = "projects"
    name = "cybersecurity"
    url = "/cybersecurity"
  [[menu.header]]
    parent = "projects"
    name = "health"
    url = "/health"